cc_binary(
    name = "parse_index",
    srcs = ["rewrite_index.cc"],
    deps = [
        "//tensorflow/core:lib",
        "//tensorflow/core:protos_all_cc",
        "//tensorflow/core/util/tensor_bundle",
        "//tensorflow/core/platform",
        "//tensorflow/core/platform:env",
        "//tensorflow:libtensorflow_framework_import_lib",
    ],
)
